### ISSUE TITLE
Add the ability to override page URL

### ISSUE THREAD

**Issue by seancdavis** [ample/gatsby-starter-ample#107]
Our current approach is to use directory structure to determine the page URL. We've heard feedback that it would be nice to have more control over that URL — to override it at the page setting.

I'm on the fence about the value of this vs just learning how the system works.

I also want to point out that Forestry is [considering](https://portal.productboard.com/forestry/1-forestry-io-roadmap/tabs/1-under-consideration) a couple feature additions that could help us in this effort.

**Comment by seancdavis** [comment]
Opening this for comments. This feel specific to Forestry. Contentful would have to have some sort of `permalink` field which would map to where the file is written, thus making a feature like this unnecessary.

Is it worth it to put in place for Forestry? My gut is that it would be useful simply because it adds better visibility to the editors in Forestry.

**Comment by dholloran-ample** [comment]
Would it be worth adding a slug field and using the slug of each page in the hierarchy to determine the URL? Since I believe finding the page name to change it is a little bit hidden if I remember correctly in Forestry. You could fall back to the filename for the slug if it does not exist. 

This would bring it more in line with other CMS implementations. Bonus points for using the title to create the slug on the initial creation screen.

**Comment by seancdavis** [comment]
@dholloran-ample Would you also allow slashes in the slug to artificially create nested pages?

Or maybe I should ask it more generically: _How would you handle page nesting while allowing overriding the URL?_

**Comment by dholloran-ample** [comment]
@seancdavis 

Assuming there is some sort of hierarchy available (if the CMS doesn't support hierarchical content that's problematic in its own right)

I'm torn on if I would allow slashes. I want to say WP does I vaguely remember using it once but ideally, every segment of the URL would have a page backing it (may not always be the case but strive for it). I think I would not expressly forbid it (Unless there is a technical reason), though I wouldn't surface that it's possible at least not in the admin.

## Page Details

1. Page 1
    - Page is at the root of the domain
    - Slug: page-1
    - URL: /page-1/
2. Page 2
    - Page is nested under Page 1
    - Slug: page-2
    - URL: /page-1/page-2/
3. Page 3
    - Page is nested under Page 2 which is nested under Page 1
    - Slug: custom-slug
    - URL: /page-1/page-2/custom-slug/

## Notes

- For Git-backed CMS, I would want to keep the file path matching the slug. Not necessarily a hard requirement just makes my brain happy since it's consistent. This may produce technical challenges and some churn in the repo (especially if it happens a lot).
- You would not allow editing of the slug for pages higher in the hierarchy. However, it would be nice if you could display `page-1/page-2/[Input to edit Page 3 slug]` in the admin

**Comment by seancdavis** [comment]
You've convinced me that, at least for git-backed CMS, this is not something we should pursue at this time. The file path should determine the page's path on the site.

We will have to solve this problem as we add Contentful support, but that will be a base-level requirement for that feature anyways. I'm going to close this.
